services:
  - type: web
    name: tovar-taxi-enhanced
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn tovar_taxi.wsgi:application"
    publishDir: "./"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: tovar_taxi.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
